### ISSUE TITLE
Add description to GitHub.

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/cfg-expr#13]
Currently the description on GitHub for this crate is blank, which makes it look odd when browsing the crates we have, it would nice to add the description "A parser and evaluator for Rust cfg() expressions." to it.

<img width="238" alt="Screenshot 2020-11-24 at 14 31 17" src="https://user-images.githubusercontent.com/4464295/100100932-d7abd480-2e61-11eb-86dc-9a4bab22441e.png">

**Comment by Jake-Shadle** [comment]
Oops, thanks for point that out!
