### ISSUE TITLE
implement PartialEq on Expression

### ISSUE THREAD

**Issue by gdesmott** [EmbarkStudios/cfg-expr#22]
I'd like to store an  `Expression` in my own struct while still being able to `#[derive(PartialEq)]` it for testing purposes.

Would you consider implementing `PartialEq` on  `Expression`? It could simply be done by comparing the  `original` fields.

**Comment by Jake-Shadle** [comment]
I _suppose_ that would be fine, but I think it would need to be documented what the `PartialEq` is actually comparing in that case, as it's not a semantic equals, just a syntactical one, but I understand the need to satisfy the requirement if you're storing an expression inside something that needs `PartialEq`.

**Comment by gdesmott** [comment]
Cool! Here is a MR doing that: #23
