### ISSUE TITLE
Use `Cow<'static, str> instead of `&'a str`?

### ISSUE THREAD

**Issue by sunshowers** [EmbarkStudios/cfg-expr#30]
**Is your feature request related to a problem? Please describe.**
It would be pretty cool to use `Cow<'static, str>` rather than `&'a str`. That would get rid of the lifetime parameter while still allowing static strings to be allocation-free.

**Describe the solution you'd like**
Switch `Arch` etc to use `Cow<'static, str>`, and drop the lifetime parameter: https://sunshowers.io/posts/open-closed-universes/#many-strings

**Describe alternatives you've considered**
Could keep the current method but it involves a lifetime param. Could switch to `String`s but that doesn't allow constants to be defined.

**Additional context**

**Comment by Jake-Shadle** [comment]
Seems reasonable!
