### ISSUE TITLE
Implement unknown answers to evaluation

### ISSUE THREAD

**Issue by sunshowers** [EmbarkStudios/cfg-expr#5]
**Is your feature request related to a problem? Please describe.**
I'd like to model the result of an evaluation where we're not sure of the answer for some predicates (most notably target features).

**Describe the solution you'd like**
Expression has a new method, say "eval3", which allows one to return an `Option<bool>` in the predicate evaluator. The Some return values would be as usual, while the None value implies unknown. The truth tables for any/all/not would be the ones found in the Kleene K3 logic (which is familiar to computer programmers as the SQL three valued logic: https://modern-sql.com/concept/three-valued-logic).

**Describe alternatives you've considered**
I thought about just setting a flag each time we hit an unknown query, but that might return unknown too often (e.g. any(true, unknown) is true,. not unknown.)

I'd be happy to send a PR upstream for this :)

**Comment by sunshowers** [comment]
You could also make eval generic :)

**Comment by sunshowers** [comment]
I've implemented the generic solution at: https://github.com/sunshowers/cfg-expr/pull/new/logic

Let me know what you think about it! Happy to clean it up and send it as a PR.

**Comment by Jake-Shadle** [comment]
That branch looks great, I'd be happy to review it. :slightly_smiling_face:
